### PR TITLE
Added logo

### PR DESCRIPTION
**Pull request by ssabnis**
I have created a logo for the project, please review

### CODE REVIEW

**Comment by debasish83** [comment]
@ssabnis can you please add a star somewhere in the logo ? It looks cool to me @rastogipankaj what do you think ?

**Comment by debasish83** [comment]
@rastogipankaj this looks cool to me now...if u r ok I will merge it in...

**Comment by debasish83** [comment]
@ssabnis you can use this https://github.com/Verizon/trapezium/issues/22

**Comment by hutashan** [comment]
Logo looks really cool.

**Comment by pramodl** [comment]
TZ* logo looks cool...

**Comment by debasish83** [comment]
TZ* +1 from me as well..

**Comment by debasish83** [comment]
@ssabnis if you can the final one, I can merge it in...

**Pull request closed without merging**
